;Program which generates the Fibonacci series (considering 0 as 1st element and 1 as 2nd element)
(defvar a)(defvar b)(defvar c)
(defun fib(x)       
	     
	 (setq a 0)(setq b 1)    
	 (format t "~%~%~D~%" a)    
	 (format t "~D~%" b) 
	 (loop for i from 2 to (- x 1)      
		  do
		        (setq c (+ a b))
		        (format t "~D~%" c)   
		        (setq a b)
		        (setq b c)    
	)
)
(princ "Enter number of terms of FIBO SEQUENCE:")
(terpri)
(defvar value)
(setq value (read))
(fib value)
